[build]
builder = 'nixpacks'

[phases.setup]
# Hilangkan '...' supaya PHP 8.2 bawaan Nixpacks TIDAK ikut terpasang!
# Tambahkan 'php83Packages.composer' agar composer tidak protes
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_22', 'nginx']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm install', 'npm run build']

[start]
# host=0.0.0.0 wajib! 127.0.0.1 bikin 502 karena Traefik gak bisa tembus
# key:generate --force agar APP_KEY terisi kalau belum di-set di env
# migrate --force untuk bikin tabel sessions (SESSION_DRIVER=database)
cmd = 'php artisan key:generate --force 2>/dev/null; php artisan storage:link --force; php artisan migrate --force; php artisan serve --host=0.0.0.0 --port=80'